const Lng = {
	Home: 'Home',
	MAIN: 'Main',
	User: 'User',
	brand: 'Skill Zhasapp',
	register: 'Register',
	login: 'Login',
	user: 'User',
	item: 'Item',
	Information: 'Information',
	item_price: 'Item price:',
	Discount: 'Discount:',
	tax: 'Tax:',
	total: 'Total:',
	Payment_gateway: 'Payment gateway',
	pay: 'Pay',
	have_giftcard: 'Have discount or gift card?',
	profile: 'Profile',
	support: 'Support',
	comments: 'Comments',
	lessons: 'Lessons',
	details: 'Details',
	leave_comment: 'Leave your comment...',
	write_support: 'Leave your support message...',
	support_is_disabled: 'Course not supported',
	send_support_massage: 'Send support massage',
	write_a_review: 'Write a review',
	write_a_review_first: 'Please write a review first',
	enroll_on_the_course: 'Enroll on the course',
	newest_courses: 'Newest courses',
	view_all: 'View All',
	most_popular_courses: 'Most popular courses',
	most_viewed_courses: 'Most viewed courses',
	featured_courses: 'Featured courses',
	home: 'Home',
	onboarding1: 'Learn everywhere',
	onboarding1_sub: 'with Skill Zhasapp',
	onboarding2: 'Teach your skills easily',
	onboarding2_sub: 'and earn money',
	onboarding3: 'Become skillful',
	onboarding3_sub: 'and invest on yourself',
	search: 'Search...',
	Category: 'Category',
	course_categories: 'Course categories',
	News: 'News',
	More: 'More',
	Latest_news: 'Latest news',
	Latest_articles: 'Latest articles',
	coming_soon_courses: 'Coming soon courses',
	Course_requests: 'Course requests',
	Follow: 'Follow',
	Courses: 'Courses',
	my_courses: 'My courses',
	back_to_categories: 'Back to categories',
	Minutes: 'Minutes',
	Followers: 'Followers',
	Bio: 'About',
	Badges: 'Badges',
	Articles: 'Articles',
	Login: 'Login',
	Send: 'Send',
	please_login: 'Please login to your account.',
	purchase_first: 'Item not purchased!',
	Email_address: 'Email address:',
	Password: 'Password:',
	re_password: 'Retype Password:',
	access_denied: 'Access denied! Your account banned until: ',
	incorrect_login: 'Incorrect username or password',
	pass_confirm_alert: 'Password and confirm password does not match.',
	password_changed: 'Password changed successfully.',
	user_not_found: 'User not found!',
	pass_change_link: 'Password change link sent to your email.',
	new_pass_email: 'New password sent to your email.',
	user_exists: 'User already exists with entered information',
	thanks_reg: 'Thanks for registration!',
	active_account_alert: 'Thanks for registration, Please check your mail and follow activation link to active your account.',
	login_request: 'Please login to your account to send request.',
	Register: 'Register',
	email_ph: 'Your email',
	username_ph: 'Your username',
	retype_ph: 'Retype password',
	realname_ph: 'Your real name',
	password_ph: 'Your password',
	enjoy_product: 'and enjoy Skill Zhasapp!',
	forget_password: 'Forgot your password?',
	Already_have_an_account: 'Already have an account?',
	Your_problem_solved: 'Your problem solved?',
	Back_to_Login: 'Back to Login',
	simply_email: 'simply by email',
	recover: 'Recover your password',
	reset_password: 'Reset Password',
	enter_email_reset_password: 'Enter your email address, Password reset link will be sent to your email.',
	username: 'Username:',
	login_to_purchase: 'Please login to purchase the course.',
	i_accept: 'I agree',
	term_rules: 'Terms & Rules',
	entered_username_exists: 'Entered username exists, Try another.',
	entered_email_exists: 'Entered email exists, Try another.',
	pass_confirmation_same: 'Those passwords didnt match, Try again.',
	active_account: 'Account activation',
	activation: 'Activation',
	successfully_done: 'Successfully done!',
	account_activation_success: 'Your account activated successfully.',
	Dashboard: 'Dashboard',
	Channels: 'Channels',
	Channel: 'Channel',
	Financial: 'Financial',
	My_courses: 'My courses',
	My_purchases: 'My purchases',
	Free: 'Free',
	Published: 'Published',
	draft: 'Draft',
	waiting: 'Waiting',
	unpublish_request: 'Unpublish Request',
	Sales: 'Sales',
	new_sales: 'New Sales',
	new_postal_sales: 'New Postal Sales',
	New_message: 'New Message',
	new_comment: 'New Comments',
	account_summary: 'Account summary',
	Account_charge: 'Account charge',
	today_sales: 'Today Sales:',
	monthly_sales: 'Monthly Sales:',
	total_sale: 'Total Sales:',
	total_income: 'Total Income:',
	Start_learning: 'Start learning and teaching',
	Ready_to_payout: 'Ready to payout:',
	start_teaching: 'Start teaching today',
	become_insructor: 'Become an instructor',
	total_purchase: 'Total Purchases:',
	current_sales_badge: 'Current Sales Badge:',
	your_total_sales: 'Total Sales:',
	Balance: 'Balances',
	charge_account: 'Charge account',
	new_ticket: 'New ticket',
	write_message: 'Write your message...',
	Attach: 'Attach file',
	close: 'Close',
	reply_message: 'Reply message',
	new_messages: 'New messages',
	Charge: 'Charge',
	purchased_items: 'Purchased items',
	sold_item: 'Sold item',
	Automatic: 'Automatic',
	manual: 'manual',
	Payoutable: 'Payoutable',
	replied: 'Replied',
	Reply: 'Reply',
	Staff: 'Staff',
	empty_field: 'The field couldnt be empty!',
	Comments: 'Comments',
	Settings: 'Settings',
	change_pass: 'Change password',
	Students: 'Students',
	Instructor: 'Instructor',
	not_defined: 'Not Defined.',
	//Settings
	account_info: 'Account info',
	realname: 'Real Name:',
	email: 'Email',
	biography: 'Biography',
	short_biography: 'Short Biography',
	province: 'Province',
	city: 'City',
	birthday: 'Birthday',
	age: 'Age',
	name: 'Name',
	Save: 'Save',
	phone_number: 'Phone Number',
	personal_info: 'Personal info',
	bank_name: 'Bank Name',
	account_number: 'Account Number',
	creditcard: 'Credit Card',
	identity_scan: 'Identity Scan',
	passport_id: 'Passport Id.',
	images: 'Images',
	avatar: 'Avatar',
	profile_cover: 'Profile Cover',
	new_password: 'New Password',
	retype_password: 'Retype Password',
	security: 'Security',
	postal: 'Postal',
	zip_code: 'Zip code',
	address: 'Address',
	financial_approved: 'Your financial information approved. To change this information contact support.',
	//Channel
	follow: 'Follow',
	unfollow: 'Unfollow',
	check: 'Check',
	incorrect_code: 'Incorrect code',
	purchase_failed: 'Purchase failed!',
	no_credit: 'Credit is not enough!',
	download: 'Download',
	become_vendor: 'Become a vendor',
	send_successfully: 'Send Successfully!',
	live: 'Live',
	Quizzes: 'Quizzes',
	Certificates: 'Certificates',
	Filter: 'Filter',
	Paid: 'Paid',
	All: 'All',
	Price: 'Price',
	Single: 'Single',
	Webinar: 'Webinar',
	Course: 'Course',
	Physical: 'Physical',
	Support: 'Support',
	filter_discount: 'Discount'
}

export { Lng }
